package com.mirror.recorder.manager;
import com.mirror.recorder.config.RecorderConfig;import com.mirror.recorder.model.Frame;import com.mirror.recorder.storage.RecordingSaveWorker;import com.mirror.recorder.storage.StorageManager;import org.apache.logging.log4j.*;import java.util.*;
public class RecorderManager{
    private static final Logger LOG=LogManager.getLogger("MirrorRecorder/Manager");public static final int MIN_SLOT=1,MAX_SLOT=100;public enum State{IDLE,RECORDING,PLAYING}public enum PendingAction{NONE,RECORD,PLAY}
    private final RecorderConfig config;private final StorageManager storage;private State state=State.IDLE;private int activeSlot=1;private static final int MAX_CACHED_SLOTS=3;private final Set<Integer> unsavedSlots=new HashSet<Integer>();
    /** Кадры держим только для последних слотов: занятый слот и слот с несохранёнными кадрами не вытесняются никогда. */
    private final Map<Integer,List<Frame>> slotData=new LinkedHashMap<Integer,List<Frame>>(16,0.75f,true){static final long serialVersionUID=1L;@Override protected boolean removeEldestEntry(Map.Entry<Integer,List<Frame>> eldest){if(eldest==null||size()<=MAX_CACHED_SLOTS)return false;Integer key=eldest.getKey();return key!=null&&!isSlotBusy(key.intValue())&&!unsavedSlots.contains(key);}};
    /** LinkedHashMap смотрит только на самый старый элемент: если он занят или не сохранён, вытеснения не будет и кадры копятся выше лимита. Убираем следующие подходящие, но никогда только что загруженный слот. */
    private void trimSlotCache(int keep){if(slotData.size()<=MAX_CACHED_SLOTS)return;for(Iterator<Map.Entry<Integer,List<Frame>>> it=slotData.entrySet().iterator();it.hasNext()&&slotData.size()>MAX_CACHED_SLOTS;){Map.Entry<Integer,List<Frame>> e=it.next();Integer key=e.getKey();if(key==null||key.intValue()==keep)continue;if(isSlotBusy(key.intValue())||unsavedSlots.contains(key))continue;it.remove();}}
    private final Map<Integer,Integer> frameCounts=new HashMap<Integer,Integer>();private final Map<Integer,String> names=new HashMap<Integer,String>(),descs=new HashMap<Integer,String>();
    private long recTicks=0,playbackRunId=0,playbackSessionId=0,playbackCompletionId=0;private boolean leftClick=false,rightClick=false,recordingStartSet=false;private int leftClicks=0,rightClicks=0;private double recordingStartX,recordingStartY,recordingStartZ;private int frameIdx=0,cooldown=0;private final PlaybackClock clock=new PlaybackClock();private PendingAction pending=PendingAction.NONE;private int pendSlot=1,delayTicks=0,unsavedWarningSlot=0,limitReachedSlot=0;private boolean playbackPaused=false;
    public RecorderManager(RecorderConfig c,StorageManager s){config=c;storage=s;selectSlot(config.getActiveSlot());storage.setSaveCallback(new RecordingSaveWorker.SaveCallback(){public void saved(int slot,boolean ok){reportSaveResult(slot,ok);}});}
    private float carryYaw=0f,carryPitch=0f;
    /** Порядок кликов внутри одного тика: ЛКМ и ПКМ пишутся в общий список, поэтому повтор не меняет их местами.
     *  Состояния «нажато/не нажато» для этого недостаточно: оно теряет и порядок, и часть событий. */
    private final int[] clickOrder=new int[Frame.MAX_CLICK_SEQ];private int clickOrderLen=0;
    private void pushClick(int button){if(clickOrderLen<clickOrder.length)clickOrder[clickOrderLen++]=button;}
    /** Клик в окне: сам факт учтён состоянием, но порядок всё равно нужен. */
    public synchronized void addClickOrder(int button){if(button==0||button==1)pushClick(button);}
    /** Порядок забирается вместе с кадром и в следующий тик не переносится. */
    public synchronized int[] consumeClickSequence(){if(clickOrderLen==0)return null;int[] out=new int[clickOrderLen];System.arraycopy(clickOrder,0,out,0,clickOrderLen);clickOrderLen=0;return out;}
    public synchronized void clearClickSequence(){clickOrderLen=0;}
    private static final int MAX_SKIPPED=4096;private final ArrayDeque<Frame> skipped=new ArrayDeque<Frame>();
    /** Ускоренный повтор: нажатия и повороты пропущенных кадров не теряются, а переходят в следующий кадр. */
    private void carry(Frame f){if(f==null)return;carryYaw+=f.dYaw;carryPitch+=f.dPitch;if(skipped.size()<MAX_SKIPPED)skipped.add(f);}
    private void clearCarry(){carryYaw=0f;carryPitch=0f;}
    /** Пропущенные при ускорении кадры не выбрасываются: обработчик повтора получает их по порядку. */
    public synchronized List<Frame> consumeSkippedFrames(){if(skipped.isEmpty())return Collections.<Frame>emptyList();List<Frame> out=new ArrayList<Frame>(skipped);skipped.clear();return out;}
    
    public synchronized float consumeCarryYaw(){float v=carryYaw;carryYaw=0f;return v;}
    public synchronized float consumeCarryPitch(){float v=carryPitch;carryPitch=0f;return v;}
    public synchronized boolean scheduleRecording(int s){if(!ok(s)||isBusy()||getSlotFrameCount(s)>0)return false;pending=PendingAction.RECORD;pendSlot=s;delayTicks=Math.max(1,config.getStartDelay()*20);return true;}public synchronized int tickDelay(){if(pending==PendingAction.NONE)return-1;if(delayTicks>0)delayTicks--;if(delayTicks<=0){exec();return 0;}return(delayTicks+19)/20;}public synchronized int getDelaySecondsRemaining(){return pending==PendingAction.NONE?-1:Math.max(0,(delayTicks+19)/20);}public synchronized void cancelPending(){pending=PendingAction.NONE;pendSlot=1;delayTicks=0;}public synchronized boolean hasPendingAction(){return pending!=PendingAction.NONE;}public synchronized int getPendingSlot(){return pendSlot;}
    private void exec(){PendingAction a=pending;int s=pendSlot;cancelPending();if(state!=State.IDLE)return;boolean started=false;if(a==PendingAction.RECORD)started=startRecording(s);else if(a==PendingAction.PLAY)started=startPlayback(s);if(!started&&a!=PendingAction.NONE)LOG.warn("Could not execute {} for slot {}",a,s);}
    public synchronized boolean startRecording(int s){if(!ok(s)||state!=State.IDLE||pending!=PendingAction.NONE||getSlotFrameCount(s)>0)return false;slotData.put(s,new ArrayList<Frame>());frameCounts.put(s,0);activeSlot=s;recTicks=0;leftClick=false;rightClick=false;leftClicks=0;rightClicks=0;clickOrderLen=0;recordingStartSet=false;state=State.RECORDING;trimSlotCache(s);return true;}public synchronized void recordTick(Frame f){if(state!=State.RECORDING||f==null)return;List<Frame> l=slotData.get(activeSlot);if(l==null){stopRecording();return;}
        // Лимит кадров: сами остановиться — норм, но молчать нельзя, флаг забирает RecordingHandler и сообщает игроку.
        if(l.size()>=StorageManager.MAX_FRAMES){limitReachedSlot=activeSlot;stopRecording();return;}if(!recordingStartSet){recordingStartX=f.x;recordingStartY=f.y;recordingStartZ=f.z;recordingStartSet=true;}l.add(f);recTicks++;frameCounts.put(activeSlot,l.size());}
    /** Смена мира при живой записи: частичное сохранение на диск, чтобы крах между мирами ничего не съел. Сама запись продолжается. */
    public synchronized void checkpointRecording(){if(state!=State.RECORDING)return;List<Frame> f=slotData.get(activeSlot);if(f==null||f.isEmpty())return;storage.queueRecordingSave(activeSlot,new ArrayList<Frame>(f),config.writeSlotSettings());}
    public synchronized boolean stopRecording(){if(state!=State.RECORDING)return false;state=State.IDLE;leftClick=false;rightClick=false;leftClicks=0;rightClicks=0;List<Frame> f=slotData.get(activeSlot);if(f==null||f.isEmpty()){frameCounts.put(activeSlot,0);recordingStartSet=false;return false;}frameCounts.put(activeSlot,f.size());unsavedSlots.add(Integer.valueOf(activeSlot));storage.queueRecordingSave(activeSlot,new ArrayList<Frame>(f),config.writeSlotSettings());recordingStartSet=false;return true;}
    /** Результат фонового сохранения: вызывается из потока сохранения, не из главного. */
    public synchronized void reportSaveResult(int slot,boolean ok){
        // Успех относится к своему снимку: флаг снимаем, только если новее ничего не летит.
        if(ok){if(storage.isSlotSettled(slot))unsavedSlots.remove(Integer.valueOf(slot));return;}
        // Слот уже удалён из памяти: предупреждать не о чем.
        if(!slotData.containsKey(Integer.valueOf(slot)))return;
        unsavedSlots.add(Integer.valueOf(slot));unsavedWarningSlot=slot;LOG.error("Recording for slot {} remains only in memory",Integer.valueOf(slot));}
    public synchronized boolean startPreparedPlayback(int s){if(!ok(s)||state!=State.IDLE||pending!=PendingAction.NONE)return false;return startPlayback(s);}public synchronized boolean startPlayback(int s){if(!ok(s)||state!=State.IDLE||pending!=PendingAction.NONE)return false;load(s);List<Frame> f=slotData.get(s);if(f==null||f.isEmpty())return false;activeSlot=s;frameIdx=0;cooldown=3;clock.reset();clearCarry();skipped.clear();playbackPaused=false;playbackSessionId++;playbackRunId++;state=State.PLAYING;return true;}public synchronized boolean advancePlayback(){if(state!=State.PLAYING)return false;if(playbackPaused)return true;List<Frame> f=slotData.get(activeSlot);if(f==null||f.isEmpty()){stopPlayback();return false;}if(cooldown>0)cooldown--;int steps=clock.advance(PlaybackClock.toMilli(config.getPlaybackSpeed()));if(steps<=0)return true;for(int i=0;i<steps;i++){frameIdx++;if(frameIdx>=f.size()){playbackCompletionId++;stopPlayback();return false;}if(i<steps-1){if(frameIdx==f.size()-1){clock.giveBack(steps-1-i);break;}carry(f.get(frameIdx));}}return true;}
    /** Пауза повтора: кадр не двигается, продолжение идёт с него же. Состояние живёт только внутри одного запуска. */
    public synchronized boolean isPaused(){return state==State.PLAYING&&playbackPaused;}
    public synchronized boolean setPlaybackPaused(boolean v){if(state!=State.PLAYING)return false;playbackPaused=v;return true;}
    public synchronized void stopPlayback(){if(state==State.PLAYING){state=State.IDLE;playbackPaused=false;frameIdx=0;cooldown=0;clock.reset();clearCarry();skipped.clear();leftClick=false;rightClick=false;leftClicks=0;rightClicks=0;}}public synchronized void stopAll(){cancelPending();if(state==State.RECORDING)stopRecording();if(state==State.PLAYING)stopPlayback();state=State.IDLE;leftClick=false;rightClick=false;leftClicks=0;rightClicks=0;recordingStartSet=false;}
    /** Импортированный слот не переписывает ваши настройки: из чужого файла они не применяются (см. StorageManager.isSlotImported). */
    public synchronized boolean selectSlot(int s){if(!ok(s)||isBusy())return false;config.setActiveSlot(s);if(!storage.isSlotImported(s))config.applySlotSettings(storage.loadSlotSettings(s));return true;}
    public synchronized boolean saveSlotSettings(int s){return ok(s)&&!isBusy()&&getSlotFrameCount(s)>0&&storage.saveSlotSettings(s,config.writeSlotSettings());}
    public synchronized boolean setSlotLoopLimit(int s,int limit){if(!ok(s)||isBusy()||getSlotFrameCount(s)<=0)return false;int v=limit<=0?0:Math.max(2,Math.min(1000,limit));if(s==config.getActiveSlot()){int prev=config.getLoopLimit();config.setLoopLimit(v);if(storage.saveSlotSettings(s,config.writeSlotSettings()))return true;config.setLoopLimit(prev);return false;}net.minecraft.nbt.NBTTagCompound t=storage.loadSlotSettings(s);if(t==null){t=new net.minecraft.nbt.NBTTagCompound();t.setInteger("SettingsVersion",1);}t.setInteger("LoopLimit",v);return storage.saveSlotSettings(s,t);}
    /** Задержка неактивного слота: сохранённая в файле слота, иначе текущая — пустой слот не подсовывает жёсткий дефолт «3». */
    public synchronized int getSlotStartDelay(int s){if(!ok(s))return 0;if(s==config.getActiveSlot())return config.getStartDelay();net.minecraft.nbt.NBTTagCompound t=storage.loadSlotSettings(s);return t!=null&&t.hasKey("StartDelay")?Math.max(0,Math.min(60,t.getInteger("StartDelay"))):config.getStartDelay();}
    public synchronized boolean setSlotStartDelay(int s,int delay){if(!ok(s)||isBusy()||getSlotFrameCount(s)<=0)return false;int v=Math.max(0,Math.min(60,delay));if(s==config.getActiveSlot()){int old=config.getStartDelay();config.setStartDelay(v);if(storage.saveSlotSettings(s,config.writeSlotSettings()))return true;config.setStartDelay(old);return false;}net.minecraft.nbt.NBTTagCompound t=storage.loadSlotSettings(s);if(t==null){t=new net.minecraft.nbt.NBTTagCompound();t.setInteger("SettingsVersion",1);}t.setInteger("StartDelay",v);return storage.saveSlotSettings(s,t);}
    public synchronized boolean setPreferredLoopMode(int s,boolean loopMode){if(!ok(s)||isBusy()||getSlotFrameCount(s)<=0)return false;if(s==config.getActiveSlot()){if(config.isPreferredLoopMode()==loopMode)return true;boolean previous=config.isPreferredLoopMode();config.setPreferredLoopMode(loopMode);if(storage.saveSlotSettings(s,config.writeSlotSettings()))return true;config.setPreferredLoopMode(previous);return false;}net.minecraft.nbt.NBTTagCompound t=storage.loadSlotSettings(s);if(t==null){t=new net.minecraft.nbt.NBTTagCompound();t.setInteger("SettingsVersion",1);}if(t.hasKey("PreferredLoop")&&t.getBoolean("PreferredLoop")==loopMode)return true;t.setBoolean("PreferredLoop",loopMode);return storage.saveSlotSettings(s,t);}
    public synchronized Frame getSlotFirstFrame(int s){if(!ok(s))return null;load(s);List<Frame> f=slotData.get(s);return f!=null&&!f.isEmpty()?f.get(0):null;}public synchronized Frame getCurrentPlaybackFrame(){List<Frame> f=slotData.get(activeSlot);return state==State.PLAYING&&f!=null&&frameIdx>=0&&frameIdx<f.size()?f.get(frameIdx):null;}public synchronized Frame getPlaybackFirstFrame(){List<Frame> f=slotData.get(activeSlot);return state==State.PLAYING&&f!=null&&!f.isEmpty()?f.get(0):null;}public synchronized Frame getPreviousPlaybackFrame(){List<Frame> f=slotData.get(activeSlot);return state==State.PLAYING&&f!=null&&frameIdx>0&&frameIdx-1<f.size()?f.get(frameIdx-1):null;}public synchronized int copyPlaybackFramesAhead(Frame[] target){if(state!=State.PLAYING||target==null||target.length==0)return 0;List<Frame> f=slotData.get(activeSlot);if(f==null||f.isEmpty())return 0;int from=Math.max(0,Math.min(frameIdx,f.size())),count=Math.min(target.length,f.size()-from);for(int i=0;i<count;i++)target[i]=f.get(from+i);for(int i=count;i<target.length&&target[i]!=null;i++)target[i]=null;return count;}
    public synchronized void load(int s){if(!ok(s)||slotData.containsKey(s))return;List<Frame> f=storage.loadRecording(s);slotData.put(s,f==null?new ArrayList<Frame>():f);frameCounts.put(s,f==null?0:f.size());trimSlotCache(s);}public synchronized boolean isSlotBusy(int s){return ok(s)&&((state!=State.IDLE&&activeSlot==s)||(pending!=PendingAction.NONE&&pendSlot==s));}public synchronized boolean canDeleteSlot(int s){return ok(s)&&getSlotFrameCount(s)>0&&!isSlotBusy(s);}public synchronized int deleteSlotStatus(int s){if(!canDeleteSlot(s))return StorageManager.DELETE_FAILED;int r=storage.deleteRecordingEx(s);if(r!=StorageManager.DELETE_FAILED)clearCache(s);return r;}
    public synchronized boolean setSlotMetadata(int s,String n,String d){if(!ok(s)||getSlotFrameCount(s)==0||isSlotBusy(s))return false;n=cleanText(n,40);d=cleanText(d,120);if(!storage.saveSlotMetadata(s,n,d))return false;names.put(s,n);descs.put(s,d);return true;}public synchronized boolean setSlotName(int s,String n){return setSlotMetadata(s,n,getSlotDescription(s));}public synchronized boolean setSlotDescription(int s,String d){return setSlotMetadata(s,getSlotName(s),d);}
    public synchronized boolean duplicateSlot(int source,int target){if(isBusy()||!ok(source)||!ok(target)||source==target||getSlotFrameCount(source)==0||getSlotFrameCount(target)>0)return false;if(!storage.duplicateRecording(source,target,com.mirror.recorder.gui.Lang.s("Дублированный слот","Duplicated slot","Дубльований слот","Duplizierter Slot","Zduplikowany slot"),com.mirror.recorder.gui.Lang.s(" (копия)"," (copy)"," (копія)"," (Kopie)"," (kopia)")))return false;clearCache(target);load(target);return true;}public synchronized String exportSlot(int s){return !isBusy()&&getSlotFrameCount(s)>0?storage.exportRecording(s):null;}public synchronized boolean importSlot(int target,String file){if(isBusy()||!ok(target)||getSlotFrameCount(target)>0)return false;if(!storage.importRecording(target,file))return false;clearCache(target);load(target);return true;}public synchronized List<String> getExportFiles(){return storage.listExportFiles();}public synchronized String getExportDirectoryPath(){return storage.getExportDirectoryPath();}
    private void clearCache(int s){slotData.remove(s);frameCounts.remove(s);names.remove(s);descs.remove(s);unsavedSlots.remove(Integer.valueOf(s));}public synchronized int getSlotFrameCount(int s){if(!ok(s))return 0;List<Frame> f=slotData.get(s);if(f!=null)return Math.min(StorageManager.MAX_FRAMES,f.size());Integer c=frameCounts.get(s);if(c==null){c=storage.peekFrameCount(s);frameCounts.put(s,c);}return Math.max(0,Math.min(StorageManager.MAX_FRAMES,c));}public synchronized long getSlotModified(int s){return storage.getLastModified(s);}public synchronized long getSlotFileSize(int s){return storage.getFileSize(s);}
    public synchronized void setLeftClickState(boolean v){leftClick=v;if(!v)leftClicks=0;}public synchronized void addLeftClick(){leftClick=true;if(leftClicks<Frame.MAX_CLICKS)leftClicks++;pushClick(0);}public synchronized int getLeftClickCount(){return leftClicks;}public synchronized boolean getLeftClickState(){return leftClick;}public synchronized void setRightClickState(boolean v){rightClick=v;if(!v)rightClicks=0;}public synchronized void addRightClick(){rightClick=true;if(rightClicks<Frame.MAX_CLICKS)rightClicks++;pushClick(1);}public synchronized int getRightClickCount(){return rightClicks;}public synchronized boolean getRightClickState(){return rightClick;}public synchronized boolean isRecording(){return state==State.RECORDING;}public synchronized boolean isPlaying(){return state==State.PLAYING;}public synchronized boolean isBusy(){return state!=State.IDLE||pending!=PendingAction.NONE;}public synchronized int getActiveOperationSlot(){return activeSlot;}public synchronized long getRecordingTickCounter(){return recTicks;}public synchronized int getCurrentFrameIndex(){return frameIdx;}public synchronized int getSimulateCooldown(){return cooldown;}public synchronized long getPlaybackRunId(){return playbackRunId;}public synchronized long getPlaybackSessionId(){return playbackSessionId;}public synchronized long getPlaybackCompletionId(){return playbackCompletionId;}public synchronized boolean hasRecordingStart(){return state==State.RECORDING&&recordingStartSet;}public synchronized double getRecordingStartX(){return recordingStartX;}public synchronized double getRecordingStartY(){return recordingStartY;}public synchronized double getRecordingStartZ(){return recordingStartZ;}public synchronized int consumeUnsavedWarningSlot(){int s=unsavedWarningSlot;unsavedWarningSlot=0;return s;}
    /** Слот, чья запись остановилась сама по лимиту кадров: сообщение игроку показывает RecordingHandler. */
    public synchronized int consumeLimitReachedSlot(){int s=limitReachedSlot;limitReachedSlot=0;return s;}
    public synchronized String getSlotName(int s){if(!ok(s))return"";if(names.containsKey(s))return names.get(s);String n=storage.loadSlotName(s);names.put(s,n==null?"":n);return n==null?"":n;}public synchronized String getSlotDescription(int s){if(!ok(s))return"";if(descs.containsKey(s))return descs.get(s);String d=storage.loadSlotDesc(s);descs.put(s,d==null?"":d);return d==null?"":d;}
    private String cleanText(String v,int max){if(v==null)return"";StringBuilder b=new StringBuilder();for(int i=0;i<v.length()&&b.length()<max;i++){char c=v.charAt(i);if(c!='\u00a7'&&!Character.isISOControl(c))b.append(c);}return b.toString().trim();}private boolean ok(int s){return s>=MIN_SLOT&&s<=MAX_SLOT;}
    /** Запись пришла извне: чат и команды из такого слота не отправляются. */
    public synchronized boolean isSlotImported(int s){return ok(s)&&storage.isImportedRecording(s);}
    /** Выгрузка мира: кадры больше не нужны. Слоты с несохранёнными кадрами не трогаем. */
    public synchronized void releaseIdleFrames(){if(isBusy())return;for(Iterator<Map.Entry<Integer,List<Frame>>> it=slotData.entrySet().iterator();it.hasNext();){Map.Entry<Integer,List<Frame>> e=it.next();if(!unsavedSlots.contains(e.getKey()))it.remove();}}
    public synchronized List<String> getTrashFiles(){return storage.listTrashFiles();}
    public synchronized int getTrashSlot(String f){return storage.trashSlot(f);}
    public synchronized int getTrashFrames(String f){return storage.trashFrames(f);}
    public synchronized long getTrashTime(String f){return storage.trashTime(f);}
    public synchronized String getTrashTitle(String f){return storage.trashTitle(f);}
    public synchronized String getTrashDirectoryPath(){return storage.getTrashDirectoryPath();}
    public synchronized boolean restoreTrash(String f,int slot){if(isBusy()||!ok(slot)||getSlotFrameCount(slot)>0)return false;if(!storage.restoreTrash(f,slot))return false;clearCache(slot);load(slot);return true;}
    public synchronized int restoreTrashToOwnSlot(String f){int s=storage.trashSlot(f);if(!ok(s))return -1;return restoreTrash(f,s)?s:-1;}
    public synchronized int undoLastDelete(){String f=storage.latestTrashFile();return f==null?-1:restoreTrashToOwnSlot(f);}
    public synchronized boolean deleteTrash(String f){return storage.deleteTrash(f);}
    public synchronized boolean clearTrash(){return storage.clearTrash();}
}
